# -*- coding: utf-8 -*-
"""MeuJogoParOuImpar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PhUg91Y0sAhdlaxmY3jRjw5-2le9OBYO
"""

jogador1 = input("->nome do jogador 1: ")
jogador2 = input("->nome do jogador 2: ")

print(f"Os jogadores são {jogador1} e {jogador2}.")

print(f"// Quem escolhe primeiro? {jogador1} ou {jogador2}?")
primeiro_jogador = input(f"digite 1 para escolher {jogador1} ou 2 para escolher {jogador2}. ->")
segundo_jogador = None

if primeiro_jogador == "1":
  primeiro_jogador = jogador1
  segundo_jogador = jogador2
elif primeiro_jogador == "2":
  primeiro_jogador = jogador2
  segundo_jogador = jogador1

print(f"//{primeiro_jogador} escolhe primeiro e {segundo_jogador} escolhe segundo.")

print("//digite 0 para escolher par e 1 para escolher ímpar")
escolha1 = input(f" {primeiro_jogador}, você quer par ou ímpar? ->")
escolha2 = None

if escolha1 == "1":
  escolha1 = "ímpar"
  escolha2 = "par"
elif escolha1 == "0":
  escolha1 = "par"
  escolha2 = "ímpar"

print(f"//{primeiro_jogador} escolheu {escolha1} e  {segundo_jogador} escolheu {escolha2}.")

print("//ESCOLHAM SEUS NÚMEROS")
numero_jogador_1 = int(input(f"numero de {primeiro_jogador}: "))
numero_jogador_2 = int(input(f"numero de {segundo_jogador}: "))

print(f"{primeiro_jogador} escolheu {numero_jogador_1} e {segundo_jogador} escolheu {numero_jogador_2}")

numero_final = numero_jogador_1 + numero_jogador_2
print(f"O número final é {numero_final}.")

if numero_final % 2 == 0:
  vencedor = "par"
else:
  vencedor = "ímpar"

if vencedor == escolha1:
  print(f"{primeiro_jogador} venceu!")
else:
  print(f"{segundo_jogador} venceu!")